---
galaxy_info:
  role_name: nginx
  namespace: rebrain
  author: Rebrain Student
  description: Install and manage an nginx server.
  company: Rebrain
  license: MIT
  min_ansible_version: "2.7"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
    - name: EL
      versions:
        - "7"
        - "8"
  galaxy_tags:
    - web
dependencies: []
